name: MinigameManager
version: 1.0.0
author: jsbrn
main: main.GameManagerPlugin
api-version: 1.16
depend: [Multiverse-Core]
commands:
  test:
    description: Developer command, not for public use.
    usage: /test
    permission: gamemanager.test
  creategame:
    description: Create a game instance for players to reserve spots in.
    usage: /creategame <map>
    permission: gamemanager.creategame
    aliases: [cg]
  joingame:
    description: Join an existing game instance that has not started yet.
    usage: /joingame <name>
    permission: gamemanager.joingame
    aliases: [jg]
  startgame:
    description: Start a game instance (teleports all registered players to the map).
    usage: /startgame <name>
    permission: gamemanager.startgame
    aliases: [sg]
