name: MinigameManager
version: 1.0.0
author: jsbrn
main: main.GameManagerPlugin
api-version: 1.16
depend: [Multiverse-Core]
commands:
  test:
    description: Developer command, not for public use.
    usage: /test
    permission: gamemanager.test
  creategame:
    description: Create a game instance for players to reserve spots in.
    usage: /creategame <map>
    permission: gamemanager.creategame
    aliases: [cg]
  next:
    description: Force a new random game.
    usage: /next
    permission: gamemanager.next
  jointeam:
    description: Switch teams.
    usage: /jointeam <teamID>
    permission: gamemanager.jointeam
