CREATE TABLE IF NOT EXISTS game_instances(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    map VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    start_date DATE DEFAULT CURRENT_DATE,
    start_time TIME DEFAULT CURRENT_TIME,
    started BOOLEAN DEFAULT FALSE,
    finished BOOLEAN DEFAULT FALSE,
    winner VARCHAR(255)
)