CREATE TABLE IF NOT EXISTS profiles(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    player_uuid VARCHAR(255) NOT NULL,
    premium BOOLEAN NOT NULL DEFAULT FALSE,
    tickets INT NOT NULL DEFAULT 0,
    credits INT NOT NULL DEFAULT 0,
    coins INT NOT NULL DEFAULT 0,
    paypal_email VARCHAR(255)
)